[package]
name = "core_lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rand = "0.8.*"
num = "0.4.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.138"

[lib]
path = "src/lib.rs"