[package]
name = "console"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
core_lib = { path = "../core_lib" }
ctrlc = "3.4"

[[bin]]
name = "evsim-console"
path = "src/main.rs"

